# Dependencia entre variables variables independientes

In [5]:
import numpy as np

Cuando tenemos el sistema con la matriz de datos $X$ y el vector de etiquetas $Y$

entre las tareas previas antes de empezar a construir un algoritmo de aprendizaje para encontrar una función $h$ tal que $h(X)=y$, consiste en analizar 

las relaciones que existen entre cada una de las variables que componen las columnas de la matriz $X$. 

Ya que pueden existir relaciones de dependencia que pueden revelar asociaciones existentes entre las varibles medidas. Finalmente se puede usar estas relaciones

para recudir el tamaño de la matriz $X$.

In [6]:
Data = [[0, 159, 49,   36,     68,     42,   57,   40],
        [1, 164, 62,   39,     73,     44,   55,   44],
        [0, 172, 65,   38,     75,     48,   58,   44],
        [0, 167, 52,   37,     73,   41.5,   58,   44],
        [0, 164, 51,   36,     71,   44.5,   54,   40], 
        [0, 161, 67,   38,     71,     44,   56,   42], 
        [0, 168, 48,   39,   72.5,     41,   54.5, 43], 
        [1, 181, 74,   43,     74,     50,   60,   47],
        [1, 183, 74,   41,     79,   47.5,   59.5, 47],
        [0, 158, 50,   36,   68.5,     44,   57,   41],
        [0, 156, 65,   36,     68,     46,   58,   41],
        [1, 173, 64,   40,     79,     48,   56.5, 47],
        [0, 158, 43,   36,     68,     43,   55,   39], 
        [1, 178, 74,   42,     75,     50,   59,   45], 
        [1, 181, 76,   43,     83,     51,   57,   43], 
        [1, 182, 91,   41,     83,     53,   59,   43], 
        [1, 176, 73,   42,     78,     48,   58,   45], 
        [0, 162, 68,   39,     72,     44,   59,   42], 
        [0, 156, 52,   36,     67,     36,   56,   41], 
        [0, 152, 45,   34,     66,     40,   55,   38], 
        [1, 181, 80,   43,     76,     49,   57,   46], 
        [1, 173, 69,   41,     74,     48,   56,   44], 
        [0, 155, 53,   36,     67,     43,   56,   38], 
        [1, 189, 87,   45,     82,     53,   61,   52], 
        [0, 170, 70,   38,     73,     45,   56,   43], 
        [1, 170, 67,   40,     77,   46.5,   58,   44.5],
        [0, 168, 56, 37.5,   70.5,     48,   60,   40]
       ]

In [7]:
nombres = ['género', 'estatura', 'peso', 'pie', 'brazo', 'espalda', 'craneo', 'rodi_tobi']

# Y  : género (0 mujer, 1 hombre), 
# X1 : estatura (en cm), 
# X2 : peso (en Kgr), 
# X3 : longitud de pie (en cm.), 
# X4 : longitud de brazo (en cm.), 
# X5 : anchura de la espalda (en cm.), 
# X6 : diámetro del cráneo (en cm.), 
# X7 : longitud entre la rodilla y el tobillo (en cm.)

# Medidas de dependencia lineal

1. Dependencias entre pares variables. La matriz de correlación

2. Entre una variable y todas las demás (coeficiente de correlación múltiple)

3. Entre pares de variables pero eliminando el efecto de las demás (correlacion parcial)

4. Entre el conjunto de todas las variables

#### Carga de datos 

In [8]:
data = np.array(Data)

data_x = data[ :, 1:len(data)]
#data_x

# 1. Dependencia por pares

La dependencia lineal entre dos variables se estudia mediante el coeficiente de correlación
lineal o simple. Este coeficiente para las variables $x_j, x_k$ es: 

$$
r_{jk} = \frac{S_{jk}}{S_{j}S_{k}} \;\;\;\;\; \mbox{donde}\;\;\;\; s_{jk} = \frac{1}{m}\sum_{i=1}^{m} (x_{ij}-\bar{x_j})(x_{ik}-\bar{x_k})
$$

Esta información para una variable multivariante puede presentarse de forma compacta en una matriz.

Se llama matriz de correlación $\textbf{R}$
a la matriz cuadrada y simétrica que tiene unos en la diagonal principal y fuera de ella los coeficientes de correlación lineal entre pares de variables.
La matriz también es semidefinida positiva.

In [9]:
import funciones_Estadisticas
from funciones_Estadisticas import correlaciones

print(correlaciones(data_x).round(2))
print('la maxima correlación aparece entre la primera y la tercera variable', '0.93')

[[1.   0.83 0.93 0.91 0.84 0.59 0.84]
 [0.83 1.   0.85 0.82 0.84 0.62 0.72]
 [0.93 0.85 1.   0.85 0.8  0.55 0.85]
 [0.91 0.82 0.85 1.   0.8  0.47 0.77]
 [0.84 0.84 0.8  0.8  1.   0.63 0.63]
 [0.59 0.62 0.55 0.47 0.63 1.   0.56]
 [0.84 0.72 0.85 0.77 0.63 0.56 1.  ]]
la maxima correlación aparece entre la primera y la tercera variable 0.93


In [10]:
nombres[1],nombres[3] 

('estatura', 'pie')

In [11]:
print('la mínima correlación aparece entre', nombres[4],nombres[6])

la mínima correlación aparece entre brazo craneo


# 2. Dependecia de cada variable y el resto: Regresión lineal múltiple


Coeficiente de determinación o coeficiente de correlación múltiple: Si una variable es combinación lineal de
las demás, y por lo tanto puede predecirse sin error con el resto, se debe eliminar de consideración. Pero bueno, sin llegar a esta situación extrema,
pueden haber variables que sean muy dependientes de las demás y conviene medir su grado de dependencia.

Los términos diagonales de la inversa de la matriz de covarianzas son precisamente las inversas de
las varianzas residuales de la regresión de cada variable con el resto.

La siguiente expresión permite obtener inmediatamente todos los coeficientes de correlación múltiple a partir de las matrices $S$ y $S^{-1}$

$$
R_j^2 = 1 - \frac{1}{s^{jj}s_{jj}}
$$

Donde $s_{jj}$ es el elemento $j$ de la diagonal de la matriz $S$ y $s^{jj}$ es el elemento $j$ de la diagonal de la matriz $S^{-1}$ 

La matriz $S^{-1}$ es 

In [12]:
from funciones_Estadisticas import Matriz_covarianzas
s_menos_uno = np.linalg.inv(Matriz_covarianzas(data_x))
s_menos_uno.round(2)

array([[ 0.14,  0.01, -0.21, -0.11, -0.07, -0.05, -0.07],
       [ 0.01,  0.04, -0.08, -0.03, -0.04, -0.04, -0.  ],
       [-0.21, -0.08,  1.26,  0.06, -0.05,  0.18, -0.29],
       [-0.11, -0.03,  0.06,  0.29, -0.04,  0.13, -0.04],
       [-0.07, -0.04, -0.05, -0.04,  0.34, -0.13,  0.15],
       [-0.05, -0.04,  0.18,  0.13, -0.13,  0.64, -0.15],
       [-0.07, -0.  , -0.29, -0.04,  0.15, -0.15,  0.5 ]])

Como se mencionó, utilizando los elementos diagonales de esta matriz y de la matriz S se puede calcular las correlaciones múltiples al cuadrado de cada variable con el resto de la siguiente manera:

Se multiplican los elementos diagonales de las matrices $S$ y $S^{-1}$.

El resultado de esta operación es:

In [13]:
DD = np.diag(s_menos_uno)*np.diag(Matriz_covarianzas(data_x))
print(DD)

[14.36721015  5.54149599  9.98983858  6.85355863  5.35489589  2.07842868
  4.75603114]


se calculan las inversas de estos elementos para obtener: 

In [14]:
DD_inverso = DD**-1
print(DD_inverso)


[0.06960294 0.18045669 0.10010172 0.1459096  0.18674499 0.4811327
 0.21025935]


Finalmente, se resta 1 al vector anterior

In [15]:
UNO_menos_DD_inverso = 1 - DD_inverso

In [16]:
print(UNO_menos_DD_inverso.round(2))

[0.93 0.82 0.9  0.85 0.81 0.52 0.79]


Y estos son los coeficientes de correlación múltiple entre cada variable y el resto. Vemos que la variable mas predicible 

In [17]:
print('La variable mas predecible por el resto es la estatura R2 = 0.9304')
print('En otros terminos, el resto de las variables explica el 93.04% de la variabilidad de esta variable')

La variable mas predecible por el resto es la estatura R2 = 0.9304
En otros terminos, el resto de las variables explica el 93.04% de la variabilidad de esta variable


### La ecuación para prever la estatura en funcion del resto es 

In [18]:
y_y = data_x[:,0]
y_y

array([159., 164., 172., 167., 164., 161., 168., 181., 183., 158., 156.,
       173., 158., 178., 181., 182., 176., 162., 156., 152., 181., 173.,
       155., 189., 170., 170., 168.])

In [19]:
X_X = data_x[:,1:len(data_x)]

X_X_X = np.hstack( (X_X, np.ones([len(X_X),1]) ))


RegresionLineal = np.linalg.lstsq(X_X_X, y_y)

In [20]:
RegresionLineal #PASA LA PRUEBA UNITARIA

(array([-0.09420402,  1.42983642,  0.73273366,  0.49446354,  0.34675894,
         0.50573069,  0.91638635]),
 array([188.11353337]),
 7,
 array([7.04191317e+02, 4.47320222e+01, 1.17560572e+01, 1.07229568e+01,
        7.92754960e+00, 4.85681001e+00, 1.16970420e-01]))

# 3 Dependencia directa entre pares: Correlaciones parciales

La dependencia directa entre dos variables controlando el efecto de las restantes se mide por
el coeficiente de correlación parcial.

In [27]:
matrizCovarianzasInev = np.linalg.inv(funciones_Estadisticas.Matriz_covarianzas(data_x))
P = funciones_Estadisticas.estandariza_matriz(matrizCovarianzasInev)

In [28]:
P

array([[ 1.93642466,  0.9359077 , -0.6837795 , -1.15549553, -0.61749218,
        -0.52054348, -0.37148691],
       [ 0.63237544,  1.54920305, -0.42253835, -0.5536696 , -0.40017144,
        -0.47814788, -0.06225443],
       [-1.5617431 , -1.66548509,  2.33681688,  0.20184947, -0.45731965,
         0.39316737, -1.3025036 ],
       [-0.55814369, -0.29286169, -0.12868478,  1.99454065, -0.41852537,
         0.20205272, -0.21456597],
       [-0.21511284, -0.51303872, -0.35724402, -0.6380891 ,  2.07624889,
        -0.8510118 ,  0.59875008],
       [-0.00246665, -0.5551031 ,  0.11341971,  0.75396237, -1.02591681,
         2.17545312, -0.71015711],
       [-0.23133384,  0.54137785, -0.85798994, -0.60309826,  0.84317656,
        -0.92097005,  2.06221795]])

In [37]:
correlacionesParciales(data_x).round(2)

array([[-1.  , -0.19,  0.48,  0.52,  0.32,  0.16,  0.27],
       [-0.19, -1.  ,  0.37,  0.29,  0.34,  0.26,  0.  ],
       [ 0.48,  0.37, -1.  , -0.11,  0.07, -0.2 ,  0.37],
       [ 0.52,  0.29, -0.11, -1.  ,  0.13, -0.31,  0.09],
       [ 0.32,  0.34,  0.07,  0.13, -1.  ,  0.29, -0.37],
       [ 0.16,  0.26, -0.2 , -0.31,  0.29, -1.  ,  0.27],
       [ 0.27,  0.  ,  0.37,  0.09, -0.37,  0.27, -1.  ]])

In [35]:
def correlacionesParciales(x):
    """
    funcion para calcular las correlaciones entre pares de variables
    """
    SdiaINV = np.diag(np.linalg.inv(funciones_Estadisticas.Matriz_covarianzas(x)))**-0.5 #son las varianzas poblacionales
    matriz_D = np.diag(SdiaINV,0) #matriz cuadrada diagonal cuya diagonal es Sdia
    intermedio = matriz_D.dot(np.linalg.inv(funciones_Estadisticas.Matriz_covarianzas(x)))
    CorrelP = -1*intermedio.dot(matriz_D)
    return CorrelP

In [38]:
correlacionesParciales(data_x)

array([[-1.        , -0.19045163,  0.48165069,  0.51584105,  0.31943604,
         0.16468267,  0.27211492],
       [-0.19045163, -1.        ,  0.37047271,  0.29497085,  0.34123019,
         0.26076059,  0.00281297],
       [ 0.48165069,  0.37047271, -1.        , -0.10729218,  0.07020131,
        -0.20371581,  0.36622824],
       [ 0.51584105,  0.29497085, -0.10729218, -1.        ,  0.12778058,
        -0.31244462,  0.09485313],
       [ 0.31943604,  0.34123019,  0.07020131,  0.12778058, -1.        ,
         0.28617015, -0.37294903],
       [ 0.16468267,  0.26076059, -0.20371581, -0.31244462,  0.28617015,
        -1.        ,  0.27004424],
       [ 0.27211492,  0.00281297,  0.36622824,  0.09485313, -0.37294903,
         0.27004424, -1.        ]])

In [39]:
Matriz_covarianzas(data_x)

array([[100.09876543, 104.34567901,  26.08847737,  44.15843621,
         33.15226337,  10.62757202,  26.15020576],
       [104.34567901, 157.80246914,  29.99794239,  50.1255144 ,
         41.61316872,  14.06378601,  27.95473251],
       [ 26.08847737,  29.99794239,   7.89780521,  11.64746228,
          8.84910837,   2.78223594,   7.40912209],
       [ 44.15843621,  50.1255144 ,  11.64746228,  23.66529492,
         15.38340192,   4.17558299,  11.53120713],
       [ 33.15226337,  41.61316872,   8.84910837,  15.38340192,
         15.57064472,   4.47085048,   7.70816187],
       [ 10.62757202,  14.06378601,   2.78223594,   4.17558299,
          4.47085048,   3.26611797,   3.10733882],
       [ 26.15020576,  27.95473251,   7.40912209,  11.53120713,
          7.70816187,   3.10733882,   9.59327846]])

In [41]:
np.linalg.inv(Matriz_covarianzas(data_x)).round(3)

array([[ 0.144,  0.014, -0.205, -0.105, -0.071, -0.05 , -0.073],
       [ 0.014,  0.035, -0.078, -0.03 , -0.037, -0.039, -0.   ],
       [-0.205, -0.078,  1.265,  0.065, -0.046,  0.183, -0.29 ],
       [-0.105, -0.03 ,  0.065,  0.29 , -0.04 ,  0.134, -0.036],
       [-0.071, -0.037, -0.046, -0.04 ,  0.344, -0.134,  0.154],
       [-0.05 , -0.039,  0.183,  0.134, -0.134,  0.636, -0.152],
       [-0.073, -0.   , -0.29 , -0.036,  0.154, -0.152,  0.496]])

In [42]:
-1*np.diag(np.linalg.inv(funciones_Estadisticas.Matriz_covarianzas(data_x)))

array([-0.14353034, -0.03511666, -1.26488794, -0.28960377, -0.34390971,
       -0.63636057, -0.49576703])

# 4 El coeficiente de dependencia

$$
D = 1- |R|^{1/(n-1)}
$$

In [45]:
Det = np.linalg.det(funciones_Estadisticas.correlaciones(data_x))
f = (len(funciones_Estadisticas.correlaciones(data_x))-1)
D = 1 - Det**(1/f)
D

0.7700370952275613

Se concluye que globalmente, la dependencia lineal explica 77% de la variabilidad de este conjunto de datos. 