# Quiz 1

**Por:** Juan Pablo Gaviria Salazar

## Punto 1

In [2]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import funciones_Estadisticas as funciones

In [2]:
data = pd.read_csv('quis11.txt', names=['x1','x2','y'])
data

x1        x2  y
0    0.051267  0.699560  1
1   -0.092742  0.684940  1
2   -0.213710  0.692250  1
3   -0.375000  0.502190  1
4   -0.513250  0.465640  1
..        ...       ... ..
113 -0.720620  0.538740  0
114 -0.593890  0.494880  0
115 -0.484450  0.999270  0
116 -0.006336  0.999270  0
117  0.632650 -0.030612  0

[118 rows x 3 columns]

In [3]:
model = smf.ols("y ~ 1 + x1 + x2", data)
result = model.fit()
print(result.summary())

OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                 -0.012
Method:                 Least Squares   F-statistic:                    0.3188
Date:                Sat, 23 May 2020   Prob (F-statistic):              0.728
Time:                        09:02:55   Log-Likelihood:                -85.300
No. Observations:                 118   AIC:                             176.6
Df Residuals:                     115   BIC:                             184.9
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4965      0.050      9.953      0.000       0.398       0.595
x

In [12]:
print('Precision obtenida {0:.3%}'.format(result.rsquared))

Precision obtenida 0.551%


## Punto 2

### Primera parte, modelo 1

In [14]:
model = smf.ols("y ~ 1 + x1 + x2 + pow(x1,2) + x1*x2 + pow(x2,2)", data)
result = model.fit()
print(result.summary())

OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.512
Model:                            OLS   Adj. R-squared:                  0.490
Method:                 Least Squares   F-statistic:                     23.49
Date:                Sat, 23 May 2020   Prob (F-statistic):           4.42e-16
Time:                        09:07:05   Log-Likelihood:                -43.314
No. Observations:                 118   AIC:                             98.63
Df Residuals:                     112   BIC:                             115.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.1801      0.074     15.850      0.000       1.033       1.328
x

In [15]:
print('Precision obtenida {0:.3%}'.format(result.rsquared))

Precision obtenida 51.187%


### Segunda parte, modelo 2

In [16]:
model = smf.ols("y ~ 1 + x1 + x2 + pow(x1,2) + x1*x2 + pow(x2,2) + pow(x1,3) + pow(x1,2)*x2 + x1*pow(x2,2) + pow(x2,3)", data)
result = model.fit()
print(result.summary())

OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.514
Model:                            OLS   Adj. R-squared:                  0.474
Method:                 Least Squares   F-statistic:                     12.70
Date:                Sat, 23 May 2020   Prob (F-statistic):           1.41e-13
Time:                        09:07:29   Log-Likelihood:                -43.046
No. Observations:                 118   AIC:                             106.1
Df Residuals:                     108   BIC:                             133.8
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.1754      0.084     14.063      0.000       1.010     

In [17]:
print('Precision obtenida {0:.3%}'.format(result.rsquared))

Precision obtenida 51.408%


## Punto 3

### Parte 1

In [18]:
data = pd.read_csv('quis12.csv')
data

Unnamed: 0     wfood    whouse     wmisc   pfood    phouse     pmisc  \
0              1  1.334811  0.737739  0.192004  0.1946  0.158281  0.176277   
1              2  1.111856  0.664423  0.290967  0.1946  0.156717  0.176102   
2              3  1.180340  0.734448  0.462126  0.1946  0.154560  0.176453   
3              4  1.349708  0.881997  0.704397  0.1946  0.155571  0.174498   
4              5  1.547675  1.202431  0.976673  0.1946  0.157675  0.173439   
...          ...       ...       ...       ...     ...       ...       ...   
1724        1725  1.606133  1.063974  1.412375  1.4263  1.668869  1.480920   
1725        1726  1.535744  1.008926  1.883404  1.4263  1.679859  1.451332   
1726        1727  1.364467  0.981355  1.806453  1.4263  1.672213  1.476982   
1727        1728  1.442346  1.012922  1.848047  1.4263  1.650462  1.481118   
1728        1729  0.311702  0.310659  0.728497  1.4263  1.628884  1.470701   

        totexp  year  income  size   pct  
0     0.037848    73       1     1  19.5  
1     0.062401    73       2     1  23.4  
2     0.086384    73       3     1  17.7  
3     0.111509    73       4     1  11.6  
4     0.136239    73       5     1   7.2  
...        ...   ...     ...   ...   ...  
1724  2.305227    92      11     6   6.0  
1725  2.514479    92      12     6   5.1  
1726  2.698539    92      13     6   5.8  
1727  2.867639    92      14     6   5.4  
1728  5.076947    92      15     6  54.8  

[1729 rows x 12 columns]

In [19]:
data = data.drop(data.columns[[0,8,9,10,11]],1)
data

wfood    whouse     wmisc   pfood    phouse     pmisc    totexp
0     1.334811  0.737739  0.192004  0.1946  0.158281  0.176277  0.037848
1     1.111856  0.664423  0.290967  0.1946  0.156717  0.176102  0.062401
2     1.180340  0.734448  0.462126  0.1946  0.154560  0.176453  0.086384
3     1.349708  0.881997  0.704397  0.1946  0.155571  0.174498  0.111509
4     1.547675  1.202431  0.976673  0.1946  0.157675  0.173439  0.136239
...        ...       ...       ...     ...       ...       ...       ...
1724  1.606133  1.063974  1.412375  1.4263  1.668869  1.480920  2.305227
1725  1.535744  1.008926  1.883404  1.4263  1.679859  1.451332  2.514479
1726  1.364467  0.981355  1.806453  1.4263  1.672213  1.476982  2.698539
1727  1.442346  1.012922  1.848047  1.4263  1.650462  1.481118  2.867639
1728  0.311702  0.310659  0.728497  1.4263  1.628884  1.470701  5.076947

[1729 rows x 7 columns]

In [20]:
npData = np.array(data)

In [21]:
s_menos_uno = np.linalg.inv(funciones.Matriz_covarianzas(npData))
s_menos_uno.round(2)

array([[ 8.70000e-01, -1.50000e+00,  4.80000e-01, -5.95000e+00,
        -3.90000e-01,  6.34000e+00,  1.00000e-01],
       [-1.50000e+00,  3.80000e+00, -1.50000e+00,  1.43300e+01,
        -5.20000e-01, -1.44300e+01,  5.40000e-01],
       [ 4.80000e-01, -1.50000e+00,  1.15000e+00, -8.91000e+00,
        -1.60000e-01,  9.52000e+00, -5.80000e-01],
       [-5.95000e+00,  1.43300e+01, -8.91000e+00,  2.38100e+03,
         2.93220e+02, -2.51086e+03,  2.02000e+00],
       [-3.90000e-01, -5.20000e-01, -1.60000e-01,  2.93220e+02,
         5.03540e+02, -8.25610e+02,  1.66000e+00],
       [ 6.34000e+00, -1.44300e+01,  9.52000e+00, -2.51086e+03,
        -8.25610e+02,  3.22867e+03, -6.77000e+00],
       [ 1.00000e-01,  5.40000e-01, -5.80000e-01,  2.02000e+00,
         1.66000e+00, -6.77000e+00,  2.16000e+00]])

In [22]:
DD = np.diag(s_menos_uno)*np.diag(funciones.Matriz_covarianzas(npData))
print(DD)

[  3.95157247   5.62748569   2.42998598 362.28621078 111.4219185
 583.69896609   2.20214363]


In [23]:
DD_inverso = DD**-1
print(DD_inverso)

[0.25306381 0.17769925 0.41152501 0.00276025 0.00897489 0.00171321
 0.45410299]


In [24]:
UNO_menos_DD_inverso = 1 - DD_inverso
print(UNO_menos_DD_inverso)

[0.74693619 0.82230075 0.58847499 0.99723975 0.99102511 0.99828679
 0.54589701]


In [25]:
maxindex = np.argmax(UNO_menos_DD_inverso)
maximo = np.max(UNO_menos_DD_inverso)
mayorCorr = list(data.columns)[maxindex]
print('La variable con mayor correlacion multiple es: '+mayorCorr+' con '+str(maximo))

La variable con mayor correlacion multiple es: pmisc con 0.9982867881252302


### Parte 2

In [26]:
model = smf.ols("pmisc ~ wfood + whouse + wmisc + pfood + phouse + totexp", data)
result = model.fit()
print(result.summary())

OLS Regression Results                            
Dep. Variable:                  pmisc   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.998
Method:                 Least Squares   F-statistic:                 1.672e+05
Date:                Sat, 23 May 2020   Prob (F-statistic):               0.00
Time:                        09:08:58   Log-Likelihood:                 4531.7
No. Observations:                1729   AIC:                            -9049.
Df Residuals:                    1722   BIC:                            -9011.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0360      0.002    -22.023      0.000      -0.039      -0.033
w

In [27]:
print('Parametros encontrados:')
print(result.params)

Parametros encontrados:
Intercept   -0.035967
wfood       -0.001965
whouse       0.004471
wmisc       -0.002948
pfood        0.777676
phouse       0.255712
totexp       0.002097
dtype: float64


### Punto 3

In [3]:
import numpy as np

In [5]:
X = np.array([[-2, -1, 0, 1, 2],[0, 0, 1, 1, 3]]).T
X

array([[-2,  0],
       [-1,  0],
       [ 0,  1],
       [ 1,  1],
       [ 2,  3]])

In [7]:
Y = np.array([0, 1, 1, 0, 1])
Y

array([0, 1, 1, 0, 1])